### ISSUE TITLE
Dependencies are broken

### ISSUE THREAD

**Issue by matiasgarciaisaia** [instedd/notifiable-diseases#14]
(See full log: https://gist.github.com/matiasgarciaisaia/05aa039eabf8b5b7cf99 )

`moment` dependency versions conflict, so the build asks the user to pick one - or fails in non-interactive builds.

We should test which of them to use and merge the change into `master`.

**Comment by bcardiff** [comment]
@spalladino told me to choose  2) moment#~2.9.0 as an option and things seems to work in my box.

**Comment by matiasgarciaisaia** [comment]
Great - I've chosen 1, but changed that to 2.

We should PR and merge this, or just fix that on `master` whenever we are sure it works OK.

**Comment by juanedi** [comment]
Fixed in aa488d7dd527ffb14a0056eea88b10b4b7e4b22d
